# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20170531_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
